apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dispatchd-prod

resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml
  - certificates.yaml

patches:
  - path: security-config-patch.yaml
    target:
      kind: ConfigMap
      name: dispatchd-config
  - path: security-secret-patch.yaml
    target:
      kind: Secret
      name: dispatchd-secrets
  - path: tls-secret-delete.yaml
    target:
      kind: Secret
      name: dispatchd-tls
  - path: control-plane-service-patch.yaml
    target:
      kind: Service
      name: control-plane
  - path: control-plane-security-patch.yaml
    target:
      kind: Deployment
      name: control-plane
  - path: worker-gateway-service-patch.yaml
    target:
      kind: Service
      name: worker-gateway
  - path: worker-gateway-security-patch.yaml
    target:
      kind: Deployment
      name: worker-gateway

images:
  - name: ghcr.io/gnix0/dispatchd-control-plane:dev
    newName: ghcr.io/gnix0/dispatchd-control-plane
    newTag: prod
  - name: ghcr.io/gnix0/dispatchd-scheduler:dev
    newName: ghcr.io/gnix0/dispatchd-scheduler
    newTag: prod
  - name: ghcr.io/gnix0/dispatchd-worker-gateway:dev
    newName: ghcr.io/gnix0/dispatchd-worker-gateway
    newTag: prod
