apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-orchestrator-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/gnix0/task-orchestrator-control-plane:dev
    newName: ghcr.io/gnix0/task-orchestrator-control-plane
    newTag: dev
  - name: ghcr.io/gnix0/task-orchestrator-scheduler:dev
    newName: ghcr.io/gnix0/task-orchestrator-scheduler
    newTag: dev
  - name: ghcr.io/gnix0/task-orchestrator-worker-gateway:dev
    newName: ghcr.io/gnix0/task-orchestrator-worker-gateway
    newTag: dev

configMapGenerator:
  - name: task-orchestrator-config
    behavior: merge
    literals:
      - APP_ENV=development-kind
      - LOG_LEVEL=debug

patches:
  - path: service-patch.yaml
