apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dispatchd-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/gnix0/dispatchd-control-plane:dev
    newName: ghcr.io/gnix0/dispatchd-control-plane
    newTag: v0.1.3
  - name: ghcr.io/gnix0/dispatchd-scheduler:dev
    newName: ghcr.io/gnix0/dispatchd-scheduler
    newTag: v0.1.3
  - name: ghcr.io/gnix0/dispatchd-worker-gateway:dev
    newName: ghcr.io/gnix0/dispatchd-worker-gateway
    newTag: v0.1.3

configMapGenerator:
  - name: dispatchd-config
    behavior: merge
    literals:
      - APP_ENV=development-kind
      - LOG_LEVEL=debug

patches:
  - path: service-patch.yaml
