apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduler
        app.kubernetes.io/component: scheduler
    spec:
      serviceAccountName: task-orchestrator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: scheduler
          image: ghcr.io/gnix0/task-orchestrator-scheduler:dev
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          envFrom:
            - configMapRef:
                name: task-orchestrator-config
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
