apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dispatchd-tls
spec:
  dnsNames:
    - control-plane
    - control-plane.dispatchd-prod-region-a.svc
    - control-plane.dispatchd-prod-region-a.svc.cluster.local
    - worker-gateway
    - worker-gateway.dispatchd-prod-region-a.svc
    - worker-gateway.dispatchd-prod-region-a.svc.cluster.local
