apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-gateway
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: dispatchd-prod-region-a
        vault.hashicorp.com/agent-inject-secret-jwt-public-key.pem: secret/data/dispatchd/prod-region-a/auth
        vault.hashicorp.com/agent-inject-template-jwt-public-key.pem: |
          {{- with secret "secret/data/dispatchd/prod-region-a/auth" -}}
          {{ .Data.data.jwt_public_key_pem }}
          {{- end -}}
