apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dispatchd-dev
  namespace: argocd
spec:
  project: dispatchd
  source:
    repoURL: https://github.com/gnix0/dispatchd.git
    targetRevision: main
    path: deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dispatchd-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
