apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dispatchd-prod-region-b
  namespace: argocd
spec:
  project: dispatchd
  source:
    repoURL: https://github.com/gnix0/dispatchd.git
    targetRevision: main
    path: deploy/overlays/prod-region-b
  destination:
    server: https://kubernetes.default.svc
    namespace: dispatchd-prod-region-b
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
