apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dispatchd
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/gnix0/dispatchd.git
  destinations:
    - namespace: dispatchd-dev
      server: https://kubernetes.default.svc
    - namespace: dispatchd-prod-region-a
      server: https://kubernetes.default.svc
    - namespace: dispatchd-prod-region-b
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
